name: Pipeline IC P8

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository               #récupération du code source
      uses: actions/checkout@v2

    - name: Setup .NET                        #configuration de .net
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0' 

    - name: Restore dependencies              #Restauration des dépendances
      run: dotnet restore

    - name: Build                              #Construction du projet
      run: dotnet build --configuration Release

    - name: Test                              #Réalisation des tests
      run: dotnet test

    - name: Publish artifacts                  #Publication des artefacts qui télécharge les DLL produits; 
      uses: actions/upload-artifact@v2
      with:
        name: dll-artifacts
        path: |
          **/TourGuideTest/obj/Debug/net7.0/*.dll
          **/TourGuideTest/obj/Debug/net7.0/ref/*.dll
          **/TourGuideTest/obj/Debug/net7.0/refint/*.dll
          **/TourGuideTest/bin/Debug/net7.0/*.dll
          **/TourGuideTest/bin/Debug/net7.0/net7.0/fine-code-coverage/build-output/*.dll
          **/Api/obj/Debug/net7.0/*.dll
          **/Api/obj/Debug/net7.0/ref/*.dll
          **/Api/obj/Debug/net7.0/refint/*.dll
          **/Api/bin/Debug/net7.0/*.dll
          **/RewardCentral/obj/Debug/net7.0/*.dll
          **/RewardCentral/obj/Debug/net7.0/ref/*.dll
          **/RewardCentral/obj/Debug/net7.0/refint/*.dll
          **/RewardCentral/bin/Debug/net7.0/*.dll
          **/TripPricer/obj/Debug/net7.0/*.dll
          **/TripPricer/obj/Debug/net7.0/ref/*.dll
          **/TripPricer/obj/Debug/net7.0/refint/*.dll
          **/TripPricer/bin/Debug/net7.0/*.dll
          **/GpsUtil/obj/Debug/net7.0/*.dll
          **/GpsUtil/obj/Debug/net7.0/ref/*.dll
          **/GpsUtil/obj/Debug/net7.0/refint/*.dll
          **/GpsUtil/bin/Debug/net7.0/*.dll


        
