name: Pipeline IC P8

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository               #récupération du code source
      uses: actions/checkout@v2

    - name: Setup .NET                        #configuration de .net
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0' 

    - name: Restore dependencies              #Restauration des dépendances
      run: dotnet restore

    - name: Build                              #Construction du projet
      run: dotnet build --configuration Release

    - name: Test                              #Réalisation des tests
      run: dotnet test

    - name: Publish artifacts                  #Publication des artefacts qui télécharge les DLL produits; 
      uses: actions/upload-artifact@v2
      with:
        name: dll-artifacts
        path: |
          **/TourGuideTest/bin/Debug/net7.0/*.dll #chemin définit dans le CSproj: bin\$(Configuration)\$(TargetFramework)\
          **/TourGuideTest/bin/Debug/net7.0/*.dll 
          **/GpsUtil/bin/Debug/net7.0/*.dll
          **/RewardCentral/bin/Debug/net7.0/*.dll
          **/TourGuide/bin/Debug/net7.0/*.dll
          **/TripPricer/bin/Debug/net7.0/*.dll


        
